### ISSUE TITLE
能不能弄个小白视频教程

### ISSUE THREAD

**Issue by qazwse4541** [wangsin/FunAnime-Frontend#3]
。。。。。。。。

**Comment by wangsin** [comment]
你说你啊？
一言不合就fork 还不点star 我咋给你弄视频教程
源代码自己看吧 而且我还没写完呢 这是前端项目几乎还没写呢
我是做后端的 前端也是自学的状态
你要是想学前端去找个大佬吧 我也是菜鸡一个
